name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@1.0.0-alpha
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
